whamcloud/lustre-collector

src/brw_stats_parser.rs, src/obdfilter.rs
Use u64 for values and dump percent and cumulative percent as they can
be derived.
=> Simplify brw_stats representation

Cargo.lock, Cargo.toml, src/base_parsers.rs, src/oss/ldlm_parser.rs, src/oss/mod.rs, src/oss/obdfilter_parser.rs, src/oss/oss_parser.rs, src/oss/top_level_parser.rs, src/stats.rs
This patch adds a parser for many stats that match: `ldlm.namespaces.{mdt-,filter-}*`.
It also refactors the data structures into top-level `HostStats` and
`TargetStats` that reflect specific targets and hosts.
=> Add parser for ldlm

Cargo.lock, Cargo.toml, README.md, src/main.rs, src/oss/ldlm_parser.rs, src/oss/obdfilter_parser.rs, src/oss/oss_parser.rs, src/oss/top_level_parser.rs, src/stats.rs
This patch adds arg parsing using `clap`.
Initially, this adds support for a format flag to output in either JSON
or YAML.
In addition, this patch removes the host field, as that should be
derived if needed in a post retrieval step.
=> Add arg parsing

src/base_parsers.rs, src/main.rs, src/mgs/mgs_parser.rs, src/mgs/mod.rs, src/oss/brw_stats_parser.rs, src/oss/ldlm_parser.rs, src/oss/obdfilter_parser.rs, src/oss/oss_parser.rs, src/parser.rs, src/stats_parser.rs, src/top_level_parser.rs, src/types.rs
This patch adds parsers for MGTs. It also refactors some file names for
better clarity and adds a variant field for clarity of which type of
target we are using.
=> Add parsers for MGTs

.travis.yml, Cargo.lock, Cargo.toml, src/base_parsers.rs, src/main.rs, src/mgs/mgs_parser.rs, src/oss/brw_stats_parser.rs, src/oss/job_stats.rs, src/oss/ldlm_parser.rs, src/oss/mod.rs, src/oss/obdfilter_parser.rs, src/oss/oss_parser.rs, src/snapshot_time.rs, src/stats_parser.rs, src/top_level_parser.rs, src/types.rs
Add support for grabbing jobstats in obdfilter.
The approach here is to eagerly take content when we know we are dealing
with jobstats, until we hit a well-known delimiter.
We then take that output, and parse it using serde_yaml into a struct,
as we know the content we've taken is valid YAML.
Ironically, the struct could later be serialized back to YAML (alongside
all the other stats) if one chooses.
=> Add OST Jobstats

.travis.yml, Cargo.lock, Cargo.toml, src/base_parsers.rs, src/main.rs, src/mgs/mgs_parser.rs, src/oss/brw_stats_parser.rs, src/oss/job_stats.rs, src/oss/ldlm_parser.rs, src/oss/obdfilter_parser.rs, src/oss/oss_parser.rs, src/parser.rs, src/snapshot_time.rs, src/stats_parser.rs, src/top_level_parser.rs
Update repo to use 2018 edition of Rust.
=> Bump to 2018 edition

Cargo.lock, Cargo.toml, README.md, lustre_collector.spec, src/lib.rs, src/types.rs
Add the `Deserialize` trait to types so they
can be deserialized. Also expose types at the top-level
for easier usage.
=> Add Deserialize trait to types

Cargo.lock, src/types.rs
Add a few `Deref` implementations for newtypes.
=> Add Deref implementations

Cargo.lock, Cargo.toml, README.md, lustre_collector.spec, src/error.rs, src/lib.rs, src/main.rs
use easy_parse instead of parse so errors contain useful information
about parsing.
=> Use easy_parse

Cargo.lock, Cargo.toml, README.md, lustre_collector.spec, src/lib.rs, src/node_stats_parsers.rs, src/snapshots/lustre_collector__node_stats_parsers__tests__cpu_stats.snap, src/snapshots/lustre_collector__node_stats_parsers__tests__empty_input.snap, src/snapshots/lustre_collector__node_stats_parsers__tests__parse_meminfo.snap, src/snapshots/lustre_collector__node_stats_parsers__tests__parse_meminfo_line.snap, src/types.rs
Add some new parsers for interpreting /proc/meminfo and /proc/stat.
These are not exposed via the cli interface, as they are not really
lustre specific.
=> Add parsers for node stats

Cargo.lock, Cargo.toml, README.md, src/node_stats_parsers.rs, src/snapshots/lustre_collector__node_stats_parsers__tests__cpu_stats.snap, src/snapshots/lustre_collector__node_stats_parsers__tests__parse_meminfo.snap, src/snapshots/lustre_collector__node_stats_parsers__tests__parse_meminfo_line.snap
Info returned from nodestats needs to be unified under the `Record`
enum.
=> Unify Node returns

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, README.md, lustre_collector.spec, src/base_parsers.rs, src/main.rs, src/mds/client_count_parser.rs, src/mds/mds_parser.rs, src/mds/mod.rs, src/mds/snapshots/lustre_collector__mds__client_count_parser__test__client_count_parser_multiple_fs.snap, src/mds/snapshots/lustre_collector__mds__client_count_parser__test__client_count_parser_one_client.snap, src/mds/snapshots/lustre_collector__mds__client_count_parser__test__client_count_parser_two_clients.snap, src/mds/snapshots/lustre_collector__mds__client_count_parser__test__client_count_parser_zero_clients.snap, src/mds/snapshots/lustre_collector__mds__client_count_parser__test__export_param.snap, src/mds/snapshots/lustre_collector__mds__client_count_parser__test__interface_clients.snap, src/mds/snapshots/lustre_collector__mds__client_count_parser__test__is_client.snap, src/mds/snapshots/lustre_collector__mds__client_count_parser__test__is_not_client.snap, src/mds/snapshots/lustre_collector__mds__client_count_parser__test__multiple_interface_clients.snap, src/mds/snapshots/lustre_collector__mds__client_count_parser__test__no_interface_clients.snap, src/parser.rs, src/snapshots/lustre_collector__parser__tests__mdt_output.snap, src/snapshots/lustre_collector__parser__tests__params.snap, src/types.rs
Add a new parser that calculates the currently connected clients on a per-fs level.
=> Implement connected client count

Cargo.lock, Cargo.toml, README.md, lustre_collector.spec, src/lnetctl_parser.rs, src/main.rs, src/oss/job_stats.rs
Fixes whamcloud/integrated-manager-for-lustre#1725.
=> Do not parse `lnetctl export` if stdout is empty.

src/lib.rs, src/main.rs, src/mgs/mgs_fs_parser.rs, src/mgs/mgs_parser.rs, src/mgs/mod.rs, src/mgs/snapshots/lustre_collector__mgs__mgs_parser__tests__params.snap, src/parser.rs, src/types.rs
Implement a new parser in lustre_collector that can take the output of lctl get_param -N mgs.MGS.live.* and parse it to show filesystem layouts
Signed-off-by: johnsonw <wjohnson@whamcloud.com>
=> EX-1552 - Implement parser to get MGS filesystems

src/mds/job_stats.rs, src/mds/mds_parser.rs, src/mds/mod.rs, src/snapshots/lustre_collector__parser__tests__params.snap, src/types.rs
Parse `lctl get_param mdt.*.job_stats` output
Example output:
```
(...)
- Target:
JobStatsMdt:
kind: MDT
param: job_stats
target: ai400x-MDT0000
value:
- job_id: bash.0
snapshot_time: 1614770669
open:
samples: 0
unit: usecs
min: 0
max: 0
sum: 0
close:
samples: 0
unit: usecs
min: 0
max: 0
sum: 0
mknod:
samples: 0
unit: usecs
min: 0
max: 0
sum: 0
link:
samples: 0
unit: usecs
min: 0
max: 0
sum: 0
unlink:
samples: 0
unit: usecs
min: 0
max: 0
sum: 0
mkdir:
samples: 0
unit: usecs
min: 0
max: 0
sum: 0
rmdir:
samples: 0
unit: usecs
min: 0
max: 0
sum: 0
rename:
samples: 0
unit: usecs
min: 0
max: 0
sum: 0
getattr:
samples: 3
unit: usecs
min: 6
max: 65
sum: 78
setattr:
samples: 0
unit: usecs
min: 0
max: 0
sum: 0
getxattr:
samples: 0
unit: usecs
min: 0
max: 0
sum: 0
setxattr:
samples: 0
unit: usecs …
```
=> Add mdt job_stats parsing

Cargo.lock, Cargo.toml, README.md, lustre_collector.spec, src/lnetctl_parser.rs, src/main.rs, src/snapshots/lustre_collector__lnetctl_parser__tests__lnet_net_parse.snap, src/snapshots/lustre_collector__lnetctl_parser__tests__lnet_parse2.snap, src/types.rs
We don't currently use the global and peers section from `lnetctl
export`. Replace it with `lnetctl net show -v 4`.
=> Remove parsing global and peers section from lnet

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, src/base_parsers.rs, src/main.rs
parsing digits contains an unwrap, which can cause any downstream consumers to panic.
Replace the unwrap with proper parsing.
In addition, modernize deps and remove unwrap in all source code.
=> Remove unwrap in digit parsing

src/fixtures/valid/ex8761-lctl.txt, src/lib.rs, src/types.rs
Serialize / Deserialize UnsignedLustreTimestamp as string.
Add test to fully serialize / deserialize an lctl get_param dump.
=> types: Fix deserialize of `UnsignedLustreTimestamp`

src/mgs/mgs_fs_parser.rs
When nodemap is enabled, `lctl get_param -N mgs.*.live.*` returns a `nodemap` value:
```
[root@localhost ~]# lctl get_param -N mgs.*.live.*
mgs.MGS.live.testfs
mgs.MGS.live.nodemap
mgs.MGS.live.params
```
This patch ignore this value (the same way we ignore `params`)
=> Ignore nodemap from 'mgs.*.live.*'

src/lib.rs, src/node_stats_parsers.rs
We should not print buffer remainder in our error output as it can be exeedingly large.
Instead, provide a message of how to reproduce the failing output.
=> Do not print buffer remainder in error

fixtures/brw_stats_empty.txt, fixtures/brw_stats_with_data.txt, fixtures/brw_stats_with_start_and_elapsed_time.txt, src/brw_stats_parser.rs, src/snapshots/lustre_collector__brw_stats_parser__tests__brw_stats.snap, src/snapshots/lustre_collector__brw_stats_parser__tests__brw_stats_with_start_and_elapsed_time.snap
Moved all multiline strings to fixtures and updated the lctl output with the new `block maps msec` field.
=> Update brw_stats test fixtures

src/base_parsers.rs, src/recovery_status_parser.rs, src/snapshots/lustre_collector__recovery_status_parser__tests__multiple.snap, src/snapshots/lustre_collector__recovery_status_parser__tests__multiple_recovering.snap, src/snapshots/lustre_collector__recovery_status_parser__tests__target_recovery_stats.snap, src/snapshots/lustre_collector__recovery_status_parser__tests__target_recovery_stats2.snap, src/snapshots/lustre_collector__recovery_status_parser__tests__waiting_for_clients.snap, src/types.rs
=> Add more recovery stats
